import { cn } from "@/lib/utils";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/help")({
  component: () => <Help />,
});

function Help() {
  return (
    <section className={cn("p-primary")}>
      <h1 className={cn("text-lg font-bold")}>
        User Documentation for GHG Emission Scenario Analysis Overview
      </h1>

      <p>
        A team of researchers aimed to understand the potential greenhouse gas
        (GHG) emissions impacts of different practices in the building industry,
        such as renovating houses instead of constructing new ones. This
        analysis is referred to as a &quot;scenario.&quot;
      </p>

      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Scenario Simulation and Data</h2>

        <h3>
          When simulating a scenario, we obtain data on potential building
          outcomes. This data includes:
        </h3>

        <ul>
          <li>- GHG emissions produced</li>
          <li>- Building use type (Residential, Non-residential)</li>
          <li>- Amount of material used per building</li>
          <li>- Country of the building</li>
        </ul>

        <p>This data is visualized using various graphs.</p>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Graph Types</h2>

        <ul>
          <li>
            - Stacked Area Graph: Best for visualizing trends as a group. By
            setting &quot;breakdown by&quot; to &quot;countries&quot; you can
            see the GHG emissions generated by all EU countries under the
            selected scenario.
          </li>
          <li>
            - Line Chart: Better for comparing GHG emissions between different
            countries.
          </li>
        </ul>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Scenario Selection and Comparison</h2>

        <p>
          On the left side of the page, you can select the scenarios you want to
          analyze:
        </p>

        <p>
          To compare two scenarios, select &quot;Scenario A&quot; and
          &quot;Scenario B.&quot; Use the &quot;display&quot; selection and/or
          the slider on the graph to switch between the scenarios.
        </p>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Custom Scenarios</h2>
        <p>
          Not satisfied with the predefined scenarios? Create your own by
          modifying the scenario parameters. We offer three categories for
          customization:
        </p>
        <ul>
          <li>- Improve</li>
          <li>- Shift</li>
          <li>- Avoid</li>
        </ul>

        <p>
          Each category has policies that you can adjust from level 1 (weak) to
          level 5 (strong). Customizing these parameters will replace the
          current &quot;Scenario A&quot; with your custom scenario.
        </p>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Data Filtering</h2>

        <p>
          The filter tab on the left side allows you to display only the data
          you are interested in.
        </p>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Data Display</h2>

        <p>
          On the right side, data can be displayed as either a graph or a table,
          depending on the tab you select. You can also choose an indicator for
          the Y-axis of the graph. Each indicator has its own unit (e.g., ktCO2,
          kt/building).
        </p>
      </section>
      <section className={cn("p-primary")}>
        <h2 className={cn("font-bold")}>Downloading Data</h2>

        <p>You can download the data in various formats:</p>
        <ul>
          <li>- Image</li>
          <li>- Spreadsheet</li>
          <li>- PDF</li>
        </ul>
        <p>
          Simply click the download button at the top right of the right section
          to choose your preferred format.
        </p>
      </section>
    </section>
  );
}
