stages:
  - test

e2e:
  stage: test
  image: docker:26.1.3-cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker compose up e2e --build --exit-code-from=e2e
# BACKEND
.backend:base:
  image: python:3.12.3-bookworm
  before_script:
    - cd backend
    - pip install poetry
    - poetry install --no-interaction

backend:lint:
  stage: test
  extends: .backend:base
  script:
    - poetry run task lint

backend:typecheck:
  extends: .backend:base
  script:
    - poetry run task typecheck

# FRONTEND
.frontend:base:
  image: node:20-bookworm
  before_script:
    - cd frontend
    - npm install -g pnpm
    - pnpm install

frontend:lint:
  stage: test
  extends: .frontend:base
  script:
    - pnpm run lint

frontend:typecheck:
  stage: test
  extends: .frontend:base
  script:
    - pnpm run typecheck
