services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3001:3001"
    depends_on:
      - backend-prod
    profiles: ["prod"]

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8081:8081"
    profiles: ["prod"]
