services:
  frontend:
    image: registry.gitlab.kuleuven.be/ae/sustainable-construction/dg-grow-eu-scenariotool/scenario-explorer/frontend/snapshot:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:8081 
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8080/ || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: registry.gitlab.kuleuven.be/ae/sustainable-construction/dg-grow-eu-scenariotool/scenario-explorer/backend/snapshot:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      GUNICORN_BIND: "0.0.0.0:8081"
    ports:
      - "8081:8081"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8081/health || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    environment:
      - CI='true'
      - APP_URL=http://frontend:8080
      - API_URL=http://backend:8081 
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
